Repository UBC-MDS/feature-selection-r, pull requests merged in 2020-03, with the labels that each got.

#18 added ecosystem to README
  README.md
Labels: documentation

#23 Implementation of RFE
  DESCRIPTION
  NAMESPACE
  R/recursive_feature_elimination.R
  man/recursive_feature_elimination.Rd
  tests/testthat.R
  tests/testthat/test-recursive_feature_elimination.R
Labels: enhancement

#26 Add simulated annealing feature selector
  R/simulated_annealing.R
  R/simulated_annealing_select.R
  tests/testthat/test-simulated_annealing.R
Labels: enhancement

#30 updated name of sim-anneal
  README.md
  man/simulated_annealing_select.Rd
Labels: documentation

#43 add dependencies and install instructions to README
  README.md
Labels: documentation

#44 added example to sim-anneal docstring
  R/simulated_annealing.R
Labels: documentation

#45 add stats dependency to docstring and update NAMESPACE
  DESCRIPTION
  R/simulated_annealing.R
  README.md
  man/simulated_annealing.Rd
Labels: documentation

#50 RFE: Use separate inputs for X and y
  R/recursive_feature_elimination.R
  R/variance_threshold_select.R
  man/recursive_feature_elimination.Rd
  man/simulated_annealing.Rd
  tests/testthat/test-recursive_feature_elimination.R
  tests/testthat/test-variance_threshold_select.R
Labels: bug

#57 Fix incorrect `variance_threshold_select`
  DESCRIPTION
  R/variance_thresholding.R
  README.Rmd
  README.md
  docs/404.html
  docs/CONDUCT.html
  docs/CONTRIBUTING.html
  docs/CONTRIBUTORS.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/articles/featureselection-vignette.html
  docs/articles/featureselection-vignette_files/header-attrs-2.1/header-attrs.js
  docs/articles/index.html
  docs/authors.html
  docs/index.html
  docs/reference/forward_selection.html
  docs/reference/index.html
  docs/reference/recursive_feature_elimination.html
  docs/reference/simulated_annealing.html
  docs/reference/variance_threshold_select.html
  docs/reference/variance_thresholding.html
  man/variance_thresholding.Rd
Labels: bug

#64 add random_state to sim_anneal
  R/simulated_annealing.R
  README.md
  man/simulated_annealing.Rd
  man/variance_thresholding.Rd
Labels: enhancement
